### PR TITLE
removing watcher

### PR DESCRIPTION
**Pull request by manute**
https://github.com/InVisionApp/kit-server/issues/285

### CODE REVIEW

**Comment by manute** [comment]
@chesleybrown  I tried to run the functional tests but I have these errors : 
```
> ./test-functional
Setting up Kubernetes...
Stopping minikube...
Stopping local Kubernetes cluster...
Connection to 192.x.x.x closed by remote host.
Machine stopped.
Closing tunnel...
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
E0220 11:51:32.211391   64516 start.go:159] Error starting host: Temporary Error: Error configuring auth on host: ssh command error:
command : sudo systemctl -f restart crio
err     : Process exited with status 5
output  : Failed to restart crio.service: Unit crio.service not found.
.

 Retrying.
E0220 11:51:37.359478   64516 start.go:159] Error starting host: Temporary Error: Error configuring auth on host: ssh command error:
command : sudo systemctl -f restart crio
err     : Process exited with status 5
output  : Failed to restart crio.service: Unit crio.service not found.
```

`minkube version: v0.25`

**Comment by manute** [comment]
ok I can run it doing first `minikube delete`

**Comment by chesleybrown** [comment]
If you don't want that watcher to run you should be able to just set `availableRequired=false` to the deployer.

**Comment by manute** [comment]
closing in favor of  https://github.com/InVisionApp/kit-server/pull/288

**Pull request closed without merging**
