### PR TITLE
Adds "raw" option

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- added "raw" option for deploying the manifests without any alterations to it
- great for when you want to rollback to a previously generated manifest that you have stored

# TODO

- [x] Verify fast-rollbacks still work when providing a "raw" manifest

### CODE REVIEW

**Comment by c1freitas** [comment]
This implementation will still work with fast-rollbacks? Will the svc file get applied or will kit update the exsiting svc to point to this deployment?

**Comment by chesleybrown** [comment]
Verified in c837921 @c1freitas

**Comment by c1freitas** [comment]
So how would this work with kitserver? If there is a manifest provided in the endpoint, the `raw` flag would be set for that deployment?

**Comment by c1freitas** [comment]
Does this require the `svc` manifest to also be present for `fast-rollback` to work?

**Comment by chesleybrown** [comment]
Yeah @c1freitas. When using `fast-rollbacks` the `svc` is tired directly to a specific deployment based on the `deployId`.

**Comment by chesleybrown** [comment]
> So how would this work with kitserver? If there is a manifest provided in the endpoint, the raw flag would be set for that deployment?

Yeah, when using raw manifests we would set the `raw` param when doing the deployment/rollback.

**Pull request merged**
