### PR TITLE
update kubectl to 1.6.7

### PR DESCRIPTION
**Pull request by c1freitas**
For Issue# https://github.com/InVisionApp/kit-deployer/issues/78

### CODE REVIEW

**Comment by chesleybrown** [comment]
I'm still not 100% convinced that this will work for us, but we can try deploying to staging and testing more thoroughly there.

I wonder if we are actually getting this error:

https://github.com/kubernetes/kubernetes/issues/25241#issuecomment-217836047

**Comment by c1freitas** [comment]
I manually ran through the steps and was able to verify the warning as well as the config annotation getting set on the newly deployed object. But you are very correct, we need to test this out. Do we want to merge this now or wait for the fast-rollback to go out?

**Comment by chesleybrown** [comment]
You can deploy now and test as the changes I'm making for fast-rollbacks will likely take most of today.

**Comment by chesleybrown** [comment]
I'm going to verify the functional tests are still working first.

**Comment by chesleybrown** [comment]
Despite my changes I'm unable to get the functional tests to pass using `v1.6.7`. Seems the api server never becomes available or we're simply unable to reach it via the http request.

It does look like hyperkube is deprecated and replaced by `minikube`. I opened https://github.com/InVisionApp/kit-deployer/issues/100 to switch to it.

**Comment by chesleybrown** [comment]
We discussed and are going to merge with it passing on 1.4.6 for the functional tests.

**Pull request merged**
