### PR TITLE
fix: added logging if available check fails

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- to help debug situations where the available check is failing, we want to log the error produced by the `status` check instead of just emitting "failure" status

### CODE REVIEW

**Comment by wincus** [comment]
lol first prize for the strangest commit ever :-)

**Comment by chesleybrown** [comment]
It's not so strange @wincus ... it's just indented a lot... did you scroll horizontally all the way over? lol

Github insists on showing tabs as `8` spaces 😖

**Comment by wincus** [comment]
ahhhh I see it now 👊

**Comment by wincus** [comment]
Looks Good! 👍

**Pull request merged**
