### PR TITLE
Automated functional tests via travis CI

### LINKED ISSUE #118: Run functional tests automatically
Looks like it might be fairly easy to use Travis CI to automatically run all the functional tests that require minikube.

https://kinvolk.io/blog/2017/10/running-kubernetes-on-travis-ci-with-minikube/

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- resolves #118 
- travis CI now runs our functional tests 👏 

# Testing

- check out the CI build https://travis-ci.org/InVisionApp/kit-deployer 😮 

# Notes

- this could be optimized in the future so that it doesn't have to build the test image from scratch each time

### CODE REVIEW

**Comment by manute** [comment]
Shall we remove codeship ??

**Comment by chesleybrown** [comment]
Codeship is still used for the unit tests and auto publishing the npm package updates.

**Comment by manute** [comment]
hmm but if the repo is public we can be able to do the same with travis 🤔

**Comment by chesleybrown** [comment]
Possibly. But it would require some rework. I don't think it's worth it as it doesn't really provide us any benefits. 🤷‍♂️

**Comment by manute** [comment]
well I can see the benefits , for example , not having 2 CI , with 2 configurations files or more that we will have to maintain. Also I think the time of waiting for every PR is bigger having 2 separate CI . Anyway, if is too much work I don't know ..

**Comment by chesleybrown** [comment]
It would be significant because it would mean we should switch the other two kit components over to travis (kit-deploymentizer, kit-image-deployer) and then we'd have to convert the npm publisher over (but we would still have to support the npm publisher for codeship as all other repos still use it under codeship). And lastly we our on a path to to migrate away from kit. I could probably think of 100 more important things to work. 😅

**Comment by chesleybrown** [comment]
@manute I had to push a fix so that if tests fail the travis CI build will actually fail too. Can you review again?

**Comment by brianhall** [comment]
Our intention for moving these to Travis was to get away from Codeship for our open sourced repo (and eliminate that encrypted, shared token). @chesleybrown Can you please flesh out your list in a little more detail and add it to a ticket so we can begin scoping that out? Thanks!

**Comment by chesleybrown** [comment]
Documented in https://github.com/InVisionApp/engineering-notes/issues/1260

**Pull request merged**
