### PR TITLE
fix: will now use random tmp dir and delete dir when done

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- kit-deployer will now use a random dir name within `/tmp` to avoid conflicts of running kit-deployer multiple times at once
- will automatically delete the tmp directory once done
- Alternative to #16 solution

### CODE REVIEW

**Comment by wincus** [comment]
Looks Good! 👍 
I like the random tmp solution better :)

**Comment by c1freitas** [comment]
Nice. +1 for UUID. 👍

**Comment by EdOverflow** [comment]
You might want to use something different than UUID, since if no CPRNG is found it will silently fallback to `Math.random()`. This could potentially allow an adversary to guess the location of the temporary file.

~~~js
if (!rng) {
  // Math.random()-based (RNG)
  //
  // If all else fails, use Math.random().  It's fast, but is of unspecified
  // quality.
  var  rnds = new Array(16);
  rng = function() {
    for (var i = 0, r; i < 16; i++) {
      if ((i & 0x03) === 0) r = Math.random() * 0x100000000;
      rnds[i] = r >>> ((i & 0x03) << 3) & 0xff;
    }

    return rnds;
  };
}
~~~

I would recommend giving [window.crypto.getRandomValues](https://developer.mozilla.org/en/docs/Web/API/RandomSource/getRandomValues) a go and then erroring out if it is not available.

**Comment by chesleybrown** [comment]
I don't think this is really applicable in our use case. The directory isn't accessible outside the service and is purely for avoiding file collisions during processing. So as long as there are no chances of of collisions (or the chances are astronomically low) it serves it's purpose.

**Pull request merged**
