### PR TITLE
feat: removing ability to delete resources

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- BREAKING: because it's to easy to mistakenly cause a mass cluster delete we are removing this functionality completely
- Because this would break backwards compatibility we are bumping the major version

### CODE REVIEW

**Comment by brianhall** [comment]
I like it. I want to make sure it's not going to make life really hard for @wincus and team, and otherwise I'm 👍 .

**Comment by chesleybrown** [comment]
It does mean whenever we want to remove a service from a cluster going forward, it will have to be manually done via `kubectl` or another tool.

**Comment by patocox** [comment]
I think that would be a fairly rare event. We would essentially be retiring a service.

**Comment by wincus** [comment]
I agree with that ... manual removing a service is not a big deal at all !

👍

**Comment by c1freitas** [comment]
Great. Note: We will still be sending this flag from the CLI and Rosie. We should add a task to update these other tools.

**Pull request merged**
